# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam
    - forbidigo
    - gomodguard
    - gosimple
    - depguard

issues:
  # Disable the default exclude list so that all excludes are explicitly
  # defined in this file.
  exclude-use-default: false


linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
      - nilness
      - shadow
      - unusedwrite
  forbidigo:
    # Forbid the following identifiers (list of regexp).
    forbid:
      - '\bioutil\b(# Use io and os packages instead of ioutil)?'
      - '\brequire\.New\b(# Use package-level functions with explicit TestingT)?'
      - '\bassert\.New\b(# Use package-level functions with explicit TestingT)?'
    # Exclude godoc examples from forbidigo checks.
    # Default: true
    exclude_godoc_examples: false
  gofmt:
    simplify: true
  gomodguard:
    blocked:
      # List of blocked modules.
      modules:
        # Blocked module.
        - github.com/hashicorp/go-msgpack:
            recommendations:
              - github.com/hashicorp/consul-net-rpc/go-msgpack
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
  depguard:
    list-type: denylist
    include-go-root: true

run:
  timeout: 10m
  concurrency: 4
  skip-dirs-use-default: false
